version: '3.1'
services:
  chainlink:
    hostname: chainlink
    image: smartcontract/chainlink:latest
    tty: true
    ports:
    - "6689:6689"
    volumes:
      - "./chainlink:/chainlink"
    env_file: .env
    secrets:
      - wallet_password
      - api_password
    command: ["node", "-p", "/run/secrets/wallet_password", "-a", "/run/secrets/api_password"]
    restart: always
volumes:
  chainlink:
secrets:
  wallet_password:
    file: ./.password
  api_password:
    file: ./.api