version: '3.1'
services:
  geth:
    hostname: geth
    image: ethereum/client-go:latest
    tty: true
    volumes:
      - "./ethereum:/ethereum"
    ports:
    - "8546:8546"
    command: ["--testnet", "--light", "--ws", "--wsaddr", "geth", "--wsport", "8546", "--wsorigins=*", "--datadir", "/ethereum"]
    restart: always
  chainlink:
    hostname: chainlink
    image: smartcontract/chainlink:latest
    tty: true
    ports:
    - "6688:6688"
    - "6689:6689"
    volumes:
      - "./chainlink:/chainlink"
    environment:
      - ETH_URL=ws://geth:8546
    env_file: .env
    secrets:
      - wallet_password
    command: ["node", "-p", "/run/secrets/wallet_password"]
    restart: always
volumes:
  chainlink:
  ethereum:
secrets:
  wallet_password:
    file: ./.password