[Eth]
NetworkId = 3
SyncMode = "light"
DatabaseCache = 768

[Node]
DataDir = "/ethereum"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPModules = ["eth", "net"]
WSHost = "0.0.0.0"
WSPort = 8546
WSOrigins = ["*"]
WSModules = ["eth"]