[parity]
base_path = "/ethereum"

[rpc]
disable = false
port = 8545
interface = "all"
apis = ["eth", "net"]

[websockets]
disable = false
port = 8546
interface = "all"
origins = ["all"]
apis = ["eth", "pubsub"]

[footprint]
cache_size = 128