[parity]
chain = "ropsten"
base_path = "/ethereum"
light = true

[rpc]
disable = false
port = 8545
interface = "all"
apis = ["eth"]

[websockets]
disable = false
port = 8546
interface = "all"
origins = ["all"]
apis = ["eth", "pubsub"]

[footprint]
cache_size = 128